// Code generated by Stan version 2.12

#include <stan/model/model_header.hpp>

namespace logit_glmm_lrvb_model_namespace {

using std::istream;
using std::string;
using std::stringstream;
using std::vector;
using stan::io::dump;
using stan::math::lgamma;
using stan::model::prob_grad;
using namespace stan::math;

typedef Eigen::Matrix<double,Eigen::Dynamic,1> vector_d;
typedef Eigen::Matrix<double,1,Eigen::Dynamic> row_vector_d;
typedef Eigen::Matrix<double,Eigen::Dynamic,Eigen::Dynamic> matrix_d;

static int current_statement_begin__;

class logit_glmm_lrvb_model : public prob_grad {
private:
    int NG;
    int N;
    int K;
    vector<int> y;
    vector<vector_d> x;
    vector<int> y_group;
    matrix_d beta_prior_var;
    vector_d beta_prior_mean;
    double mu_prior_mean;
    double mu_prior_var;
    double tau_prior_alpha;
    double tau_prior_beta;
    int N_sim;
    vector_d std_normal_draws;
public:
    logit_glmm_lrvb_model(stan::io::var_context& context__,
        std::ostream* pstream__ = 0)
        : prob_grad(0) {
        typedef boost::ecuyer1988 rng_t;
        rng_t base_rng(0);  // 0 seed default
        ctor_body(context__, base_rng, pstream__);
    }

    template <class RNG>
    logit_glmm_lrvb_model(stan::io::var_context& context__,
        RNG& base_rng__,
        std::ostream* pstream__ = 0)
        : prob_grad(0) {
        ctor_body(context__, base_rng__, pstream__);
    }

    template <class RNG>
    void ctor_body(stan::io::var_context& context__,
                   RNG& base_rng__,
                   std::ostream* pstream__) {
        current_statement_begin__ = -1;

        static const char* function__ = "logit_glmm_lrvb_model_namespace::logit_glmm_lrvb_model";
        (void) function__; // dummy call to supress warning
        size_t pos__;
        (void) pos__; // dummy call to supress warning
        std::vector<int> vals_i__;
        std::vector<double> vals_r__;
        context__.validate_dims("data initialization", "NG", "int", context__.to_vec());
        NG = int(0);
        vals_i__ = context__.vals_i("NG");
        pos__ = 0;
        NG = vals_i__[pos__++];
        context__.validate_dims("data initialization", "N", "int", context__.to_vec());
        N = int(0);
        vals_i__ = context__.vals_i("N");
        pos__ = 0;
        N = vals_i__[pos__++];
        context__.validate_dims("data initialization", "K", "int", context__.to_vec());
        K = int(0);
        vals_i__ = context__.vals_i("K");
        pos__ = 0;
        K = vals_i__[pos__++];
        context__.validate_dims("data initialization", "y", "int", context__.to_vec(N));
        validate_non_negative_index("y", "N", N);
        y = std::vector<int>(N,int(0));
        vals_i__ = context__.vals_i("y");
        pos__ = 0;
        size_t y_limit_0__ = N;
        for (size_t i_0__ = 0; i_0__ < y_limit_0__; ++i_0__) {
            y[i_0__] = vals_i__[pos__++];
        }
        validate_non_negative_index("x", "N", N);
        validate_non_negative_index("x", "K", K);
        x = std::vector<vector_d>(N,vector_d(static_cast<Eigen::VectorXd::Index>(K)));
        context__.validate_dims("data initialization", "x", "vector_d", context__.to_vec(N,K));
        vals_r__ = context__.vals_r("x");
        pos__ = 0;
        size_t x_i_vec_lim__ = K;
        for (size_t i_vec__ = 0; i_vec__ < x_i_vec_lim__; ++i_vec__) {
            size_t x_limit_0__ = N;
            for (size_t i_0__ = 0; i_0__ < x_limit_0__; ++i_0__) {
                x[i_0__][i_vec__] = vals_r__[pos__++];
            }
        }
        context__.validate_dims("data initialization", "y_group", "int", context__.to_vec(N));
        validate_non_negative_index("y_group", "N", N);
        y_group = std::vector<int>(N,int(0));
        vals_i__ = context__.vals_i("y_group");
        pos__ = 0;
        size_t y_group_limit_0__ = N;
        for (size_t i_0__ = 0; i_0__ < y_group_limit_0__; ++i_0__) {
            y_group[i_0__] = vals_i__[pos__++];
        }
        context__.validate_dims("data initialization", "beta_prior_var", "matrix_d", context__.to_vec(K,K));
        validate_non_negative_index("beta_prior_var", "K", K);
        validate_non_negative_index("beta_prior_var", "K", K);
        beta_prior_var = matrix_d(static_cast<Eigen::VectorXd::Index>(K),static_cast<Eigen::VectorXd::Index>(K));
        vals_r__ = context__.vals_r("beta_prior_var");
        pos__ = 0;
        size_t beta_prior_var_m_mat_lim__ = K;
        size_t beta_prior_var_n_mat_lim__ = K;
        for (size_t n_mat__ = 0; n_mat__ < beta_prior_var_n_mat_lim__; ++n_mat__) {
            for (size_t m_mat__ = 0; m_mat__ < beta_prior_var_m_mat_lim__; ++m_mat__) {
                beta_prior_var(m_mat__,n_mat__) = vals_r__[pos__++];
            }
        }
        validate_non_negative_index("beta_prior_mean", "K", K);
        beta_prior_mean = vector_d(static_cast<Eigen::VectorXd::Index>(K));
        context__.validate_dims("data initialization", "beta_prior_mean", "vector_d", context__.to_vec(K));
        vals_r__ = context__.vals_r("beta_prior_mean");
        pos__ = 0;
        size_t beta_prior_mean_i_vec_lim__ = K;
        for (size_t i_vec__ = 0; i_vec__ < beta_prior_mean_i_vec_lim__; ++i_vec__) {
            beta_prior_mean[i_vec__] = vals_r__[pos__++];
        }
        context__.validate_dims("data initialization", "mu_prior_mean", "double", context__.to_vec());
        mu_prior_mean = double(0);
        vals_r__ = context__.vals_r("mu_prior_mean");
        pos__ = 0;
        mu_prior_mean = vals_r__[pos__++];
        context__.validate_dims("data initialization", "mu_prior_var", "double", context__.to_vec());
        mu_prior_var = double(0);
        vals_r__ = context__.vals_r("mu_prior_var");
        pos__ = 0;
        mu_prior_var = vals_r__[pos__++];
        context__.validate_dims("data initialization", "tau_prior_alpha", "double", context__.to_vec());
        tau_prior_alpha = double(0);
        vals_r__ = context__.vals_r("tau_prior_alpha");
        pos__ = 0;
        tau_prior_alpha = vals_r__[pos__++];
        context__.validate_dims("data initialization", "tau_prior_beta", "double", context__.to_vec());
        tau_prior_beta = double(0);
        vals_r__ = context__.vals_r("tau_prior_beta");
        pos__ = 0;
        tau_prior_beta = vals_r__[pos__++];
        context__.validate_dims("data initialization", "N_sim", "int", context__.to_vec());
        N_sim = int(0);
        vals_i__ = context__.vals_i("N_sim");
        pos__ = 0;
        N_sim = vals_i__[pos__++];
        validate_non_negative_index("std_normal_draws", "N_sim", N_sim);
        std_normal_draws = vector_d(static_cast<Eigen::VectorXd::Index>(N_sim));
        context__.validate_dims("data initialization", "std_normal_draws", "vector_d", context__.to_vec(N_sim));
        vals_r__ = context__.vals_r("std_normal_draws");
        pos__ = 0;
        size_t std_normal_draws_i_vec_lim__ = N_sim;
        for (size_t i_vec__ = 0; i_vec__ < std_normal_draws_i_vec_lim__; ++i_vec__) {
            std_normal_draws[i_vec__] = vals_r__[pos__++];
        }

        // validate data
        check_greater_or_equal(function__,"NG",NG,0);
        check_greater_or_equal(function__,"N",N,0);
        check_greater_or_equal(function__,"K",K,0);
        for (int k0__ = 0; k0__ < N; ++k0__) {
            check_greater_or_equal(function__,"y[k0__]",y[k0__],0);
            check_less_or_equal(function__,"y[k0__]",y[k0__],1);
        }
        check_greater_or_equal(function__,"mu_prior_var",mu_prior_var,0);
        check_greater_or_equal(function__,"tau_prior_alpha",tau_prior_alpha,0);
        check_greater_or_equal(function__,"tau_prior_beta",tau_prior_beta,0);
        check_greater_or_equal(function__,"N_sim",N_sim,0);

        double DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning


        // initialize transformed variables to avoid seg fault on val access

        try {
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e,current_statement_begin__);
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }

        // validate transformed data

        // set parameter ranges
        num_params_r__ = 0U;
        param_ranges_i__.clear();
        num_params_r__ += K;
        num_params_r__ += ((K * (K - 1)) / 2 + K);
        ++num_params_r__;
        ++num_params_r__;
        ++num_params_r__;
        ++num_params_r__;
        num_params_r__ += NG;
        num_params_r__ += NG;
    }

    ~logit_glmm_lrvb_model() { }


    void transform_inits(const stan::io::var_context& context__,
                         std::vector<int>& params_i__,
                         std::vector<double>& params_r__,
                         std::ostream* pstream__) const {
        stan::io::writer<double> writer__(params_r__,params_i__);
        size_t pos__;
        (void) pos__; // dummy call to supress warning
        std::vector<double> vals_r__;
        std::vector<int> vals_i__;

        if (!(context__.contains_r("e_beta")))
            throw std::runtime_error("variable e_beta missing");
        vals_r__ = context__.vals_r("e_beta");
        pos__ = 0U;
        context__.validate_dims("initialization", "e_beta", "vector_d", context__.to_vec(K));
        vector_d e_beta(static_cast<Eigen::VectorXd::Index>(K));
        for (int j1__ = 0U; j1__ < K; ++j1__)
            e_beta(j1__) = vals_r__[pos__++];
        try {
            writer__.vector_unconstrain(e_beta);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable e_beta: ") + e.what());
        }

        if (!(context__.contains_r("cov_beta")))
            throw std::runtime_error("variable cov_beta missing");
        vals_r__ = context__.vals_r("cov_beta");
        pos__ = 0U;
        context__.validate_dims("initialization", "cov_beta", "matrix_d", context__.to_vec(K,K));
        matrix_d cov_beta(static_cast<Eigen::VectorXd::Index>(K),static_cast<Eigen::VectorXd::Index>(K));
        for (int j2__ = 0U; j2__ < K; ++j2__)
            for (int j1__ = 0U; j1__ < K; ++j1__)
                cov_beta(j1__,j2__) = vals_r__[pos__++];
        try {
            writer__.cov_matrix_unconstrain(cov_beta);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable cov_beta: ") + e.what());
        }

        if (!(context__.contains_r("e_mu")))
            throw std::runtime_error("variable e_mu missing");
        vals_r__ = context__.vals_r("e_mu");
        pos__ = 0U;
        context__.validate_dims("initialization", "e_mu", "double", context__.to_vec());
        double e_mu(0);
        e_mu = vals_r__[pos__++];
        try {
            writer__.scalar_unconstrain(e_mu);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable e_mu: ") + e.what());
        }

        if (!(context__.contains_r("var_mu")))
            throw std::runtime_error("variable var_mu missing");
        vals_r__ = context__.vals_r("var_mu");
        pos__ = 0U;
        context__.validate_dims("initialization", "var_mu", "double", context__.to_vec());
        double var_mu(0);
        var_mu = vals_r__[pos__++];
        try {
            writer__.scalar_lb_unconstrain(0,var_mu);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable var_mu: ") + e.what());
        }

        if (!(context__.contains_r("tau_shape")))
            throw std::runtime_error("variable tau_shape missing");
        vals_r__ = context__.vals_r("tau_shape");
        pos__ = 0U;
        context__.validate_dims("initialization", "tau_shape", "double", context__.to_vec());
        double tau_shape(0);
        tau_shape = vals_r__[pos__++];
        try {
            writer__.scalar_lb_unconstrain(0,tau_shape);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable tau_shape: ") + e.what());
        }

        if (!(context__.contains_r("tau_rate")))
            throw std::runtime_error("variable tau_rate missing");
        vals_r__ = context__.vals_r("tau_rate");
        pos__ = 0U;
        context__.validate_dims("initialization", "tau_rate", "double", context__.to_vec());
        double tau_rate(0);
        tau_rate = vals_r__[pos__++];
        try {
            writer__.scalar_lb_unconstrain(0,tau_rate);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable tau_rate: ") + e.what());
        }

        if (!(context__.contains_r("e_u")))
            throw std::runtime_error("variable e_u missing");
        vals_r__ = context__.vals_r("e_u");
        pos__ = 0U;
        context__.validate_dims("initialization", "e_u", "vector_d", context__.to_vec(NG));
        vector_d e_u(static_cast<Eigen::VectorXd::Index>(NG));
        for (int j1__ = 0U; j1__ < NG; ++j1__)
            e_u(j1__) = vals_r__[pos__++];
        try {
            writer__.vector_unconstrain(e_u);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable e_u: ") + e.what());
        }

        if (!(context__.contains_r("var_u")))
            throw std::runtime_error("variable var_u missing");
        vals_r__ = context__.vals_r("var_u");
        pos__ = 0U;
        context__.validate_dims("initialization", "var_u", "vector_d", context__.to_vec(NG));
        vector_d var_u(static_cast<Eigen::VectorXd::Index>(NG));
        for (int j1__ = 0U; j1__ < NG; ++j1__)
            var_u(j1__) = vals_r__[pos__++];
        try {
            writer__.vector_lb_unconstrain(0,var_u);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable var_u: ") + e.what());
        }

        params_r__ = writer__.data_r();
        params_i__ = writer__.data_i();
    }

    void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                         std::ostream* pstream__) const {
      std::vector<double> params_r_vec;
      std::vector<int> params_i_vec;
      transform_inits(context, params_i_vec, params_r_vec, pstream__);
      params_r.resize(params_r_vec.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r(i) = params_r_vec[i];
    }


    template <bool propto__, bool jacobian__, typename T__>
    T__ log_prob(vector<T__>& params_r__,
                 vector<int>& params_i__,
                 std::ostream* pstream__ = 0) const {

        T__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning

        T__ lp__(0.0);
        stan::math::accumulator<T__> lp_accum__;

        // model parameters
        stan::io::reader<T__> in__(params_r__,params_i__);

        Eigen::Matrix<T__,Eigen::Dynamic,1>  e_beta;
        (void) e_beta;  // dummy to suppress unused var warning
        if (jacobian__)
            e_beta = in__.vector_constrain(K,lp__);
        else
            e_beta = in__.vector_constrain(K);

        Eigen::Matrix<T__,Eigen::Dynamic,Eigen::Dynamic>  cov_beta;
        (void) cov_beta;  // dummy to suppress unused var warning
        if (jacobian__)
            cov_beta = in__.cov_matrix_constrain(K,lp__);
        else
            cov_beta = in__.cov_matrix_constrain(K);

        T__ e_mu;
        (void) e_mu;  // dummy to suppress unused var warning
        if (jacobian__)
            e_mu = in__.scalar_constrain(lp__);
        else
            e_mu = in__.scalar_constrain();

        T__ var_mu;
        (void) var_mu;  // dummy to suppress unused var warning
        if (jacobian__)
            var_mu = in__.scalar_lb_constrain(0,lp__);
        else
            var_mu = in__.scalar_lb_constrain(0);

        T__ tau_shape;
        (void) tau_shape;  // dummy to suppress unused var warning
        if (jacobian__)
            tau_shape = in__.scalar_lb_constrain(0,lp__);
        else
            tau_shape = in__.scalar_lb_constrain(0);

        T__ tau_rate;
        (void) tau_rate;  // dummy to suppress unused var warning
        if (jacobian__)
            tau_rate = in__.scalar_lb_constrain(0,lp__);
        else
            tau_rate = in__.scalar_lb_constrain(0);

        Eigen::Matrix<T__,Eigen::Dynamic,1>  e_u;
        (void) e_u;  // dummy to suppress unused var warning
        if (jacobian__)
            e_u = in__.vector_constrain(NG,lp__);
        else
            e_u = in__.vector_constrain(NG);

        Eigen::Matrix<T__,Eigen::Dynamic,1>  var_u;
        (void) var_u;  // dummy to suppress unused var warning
        if (jacobian__)
            var_u = in__.vector_lb_constrain(0,NG,lp__);
        else
            var_u = in__.vector_lb_constrain(0,NG);


        // transformed parameters
        Eigen::Matrix<T__,Eigen::Dynamic,Eigen::Dynamic>  e_beta_outer(static_cast<Eigen::VectorXd::Index>(K),static_cast<Eigen::VectorXd::Index>(K));
        (void) e_beta_outer;  // dummy to suppress unused var warning
        T__ e_mu2;
        (void) e_mu2;  // dummy to suppress unused var warning
        T__ e_tau;
        (void) e_tau;  // dummy to suppress unused var warning
        T__ e_log_tau;
        (void) e_log_tau;  // dummy to suppress unused var warning
        Eigen::Matrix<T__,Eigen::Dynamic,Eigen::Dynamic>  beta_prior_info(static_cast<Eigen::VectorXd::Index>(K),static_cast<Eigen::VectorXd::Index>(K));
        (void) beta_prior_info;  // dummy to suppress unused var warning
        Eigen::Matrix<T__,Eigen::Dynamic,1>  e_log_1mp(static_cast<Eigen::VectorXd::Index>(N));
        (void) e_log_1mp;  // dummy to suppress unused var warning
        Eigen::Matrix<T__,Eigen::Dynamic,1>  logit_p_mean(static_cast<Eigen::VectorXd::Index>(N));
        (void) logit_p_mean;  // dummy to suppress unused var warning
        Eigen::Matrix<T__,Eigen::Dynamic,1>  logit_p_sd(static_cast<Eigen::VectorXd::Index>(N));
        (void) logit_p_sd;  // dummy to suppress unused var warning

        // initialize transformed variables to avoid seg fault on val access
        stan::math::fill(e_beta_outer,DUMMY_VAR__);
        stan::math::fill(e_mu2,DUMMY_VAR__);
        stan::math::fill(e_tau,DUMMY_VAR__);
        stan::math::fill(e_log_tau,DUMMY_VAR__);
        stan::math::fill(beta_prior_info,DUMMY_VAR__);
        stan::math::fill(e_log_1mp,DUMMY_VAR__);
        stan::math::fill(logit_p_mean,DUMMY_VAR__);
        stan::math::fill(logit_p_sd,DUMMY_VAR__);

        try {
            current_statement_begin__ = 54;
            stan::math::assign(e_beta_outer, add(multiply(e_beta,transpose(e_beta)),cov_beta));
            current_statement_begin__ = 55;
            stan::math::assign(e_mu2, (pow(e_mu,2) + var_mu));
            current_statement_begin__ = 56;
            stan::math::assign(e_tau, (tau_shape / tau_rate));
            current_statement_begin__ = 57;
            stan::math::assign(e_log_tau, (digamma(tau_shape) - log(tau_rate)));
            current_statement_begin__ = 60;
            for (int n = 1; n <= N; ++n) {
                current_statement_begin__ = 62;
                stan::math::assign(get_base1_lhs(logit_p_mean,n,"logit_p_mean",1), (dot_product(get_base1(x,n,"x",1),e_beta) + get_base1(e_u,(get_base1(y_group,n,"y_group",1) + 1),"e_u",1)));
                current_statement_begin__ = 63;
                stan::math::assign(get_base1_lhs(logit_p_sd,n,"logit_p_sd",1), sqrt((dot_product(get_base1(x,n,"x",1),multiply(e_beta_outer,get_base1(x,n,"x",1))) + get_base1(var_u,(get_base1(y_group,n,"y_group",1) + 1),"var_u",1))));
                current_statement_begin__ = 67;
                stan::math::assign(get_base1_lhs(e_log_1mp,n,"e_log_1mp",1), 0);
                current_statement_begin__ = 68;
                for (int n_sim = 1; n_sim <= N_sim; ++n_sim) {
                    current_statement_begin__ = 69;
                    stan::math::assign(get_base1_lhs(e_log_1mp,n,"e_log_1mp",1), (get_base1(e_log_1mp,n,"e_log_1mp",1) + log1m_inv_logit(((get_base1(logit_p_sd,n,"logit_p_sd",1) * get_base1(std_normal_draws,n_sim,"std_normal_draws",1)) + get_base1(logit_p_mean,n,"logit_p_mean",1)))));
                }
                current_statement_begin__ = 72;
                stan::math::assign(get_base1_lhs(e_log_1mp,n,"e_log_1mp",1), (get_base1(e_log_1mp,n,"e_log_1mp",1) / N_sim));
            }
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e,current_statement_begin__);
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }

        // validate transformed parameters
        for (int i0__ = 0; i0__ < K; ++i0__) {
            for (int i1__ = 0; i1__ < K; ++i1__) {
                if (stan::math::is_uninitialized(e_beta_outer(i0__,i1__))) {
                    std::stringstream msg__;
                    msg__ << "Undefined transformed parameter: e_beta_outer" << '[' << i0__ << ']' << '[' << i1__ << ']';
                    throw std::runtime_error(msg__.str());
                }
            }
        }
        if (stan::math::is_uninitialized(e_mu2)) {
            std::stringstream msg__;
            msg__ << "Undefined transformed parameter: e_mu2";
            throw std::runtime_error(msg__.str());
        }
        if (stan::math::is_uninitialized(e_tau)) {
            std::stringstream msg__;
            msg__ << "Undefined transformed parameter: e_tau";
            throw std::runtime_error(msg__.str());
        }
        if (stan::math::is_uninitialized(e_log_tau)) {
            std::stringstream msg__;
            msg__ << "Undefined transformed parameter: e_log_tau";
            throw std::runtime_error(msg__.str());
        }
        for (int i0__ = 0; i0__ < K; ++i0__) {
            for (int i1__ = 0; i1__ < K; ++i1__) {
                if (stan::math::is_uninitialized(beta_prior_info(i0__,i1__))) {
                    std::stringstream msg__;
                    msg__ << "Undefined transformed parameter: beta_prior_info" << '[' << i0__ << ']' << '[' << i1__ << ']';
                    throw std::runtime_error(msg__.str());
                }
            }
        }
        for (int i0__ = 0; i0__ < N; ++i0__) {
            if (stan::math::is_uninitialized(e_log_1mp(i0__))) {
                std::stringstream msg__;
                msg__ << "Undefined transformed parameter: e_log_1mp" << '[' << i0__ << ']';
                throw std::runtime_error(msg__.str());
            }
        }
        for (int i0__ = 0; i0__ < N; ++i0__) {
            if (stan::math::is_uninitialized(logit_p_mean(i0__))) {
                std::stringstream msg__;
                msg__ << "Undefined transformed parameter: logit_p_mean" << '[' << i0__ << ']';
                throw std::runtime_error(msg__.str());
            }
        }
        for (int i0__ = 0; i0__ < N; ++i0__) {
            if (stan::math::is_uninitialized(logit_p_sd(i0__))) {
                std::stringstream msg__;
                msg__ << "Undefined transformed parameter: logit_p_sd" << '[' << i0__ << ']';
                throw std::runtime_error(msg__.str());
            }
        }

        const char* function__ = "validate transformed params";
        (void) function__;  // dummy to suppress unused var warning

        // model body
        try {
            current_statement_begin__ = 81;
            lp_accum__.add(((0.5 * ((e_mu2 + ((2 * e_mu) * mu_prior_mean)) + pow(mu_prior_mean,2))) / mu_prior_mean));
            current_statement_begin__ = 82;
            lp_accum__.add((((tau_prior_alpha - 1) * e_log_tau) - (tau_rate * e_tau)));
            current_statement_begin__ = 83;
            lp_accum__.add((0.5 * ((trace(mdivide_left_spd(beta_prior_var,e_beta_outer)) + dot_product(e_beta,mdivide_left_spd(beta_prior_var,beta_prior_mean))) + dot_product(beta_prior_mean,mdivide_left_spd(beta_prior_var,e_beta)))));
            current_statement_begin__ = 89;
            for (int g = 1; g <= NG; ++g) {
                current_statement_begin__ = 91;
                lp_accum__.add(((0.5 * e_tau) * ((e_mu2 + ((2 * e_mu) * get_base1(e_u,g,"e_u",1))) + (pow(get_base1(e_u,g,"e_u",1),2) + get_base1(var_u,g,"var_u",1)))));
            }
            current_statement_begin__ = 94;
            for (int n = 1; n <= N; ++n) {
                current_statement_begin__ = 98;
                lp_accum__.add(((get_base1(y,n,"y",1) * get_base1(logit_p_mean,n,"logit_p_mean",1)) + get_base1(e_log_1mp,n,"e_log_1mp",1)));
            }
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e,current_statement_begin__);
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }

        lp_accum__.add(lp__);
        return lp_accum__.sum();

    } // log_prob()

    template <bool propto, bool jacobian, typename T_>
    T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
               std::ostream* pstream = 0) const {
      std::vector<T_> vec_params_r;
      vec_params_r.reserve(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        vec_params_r.push_back(params_r(i));
      std::vector<int> vec_params_i;
      return log_prob<propto,jacobian,T_>(vec_params_r, vec_params_i, pstream);
    }


    void get_param_names(std::vector<std::string>& names__) const {
        names__.resize(0);
        names__.push_back("e_beta");
        names__.push_back("cov_beta");
        names__.push_back("e_mu");
        names__.push_back("var_mu");
        names__.push_back("tau_shape");
        names__.push_back("tau_rate");
        names__.push_back("e_u");
        names__.push_back("var_u");
        names__.push_back("e_beta_outer");
        names__.push_back("e_mu2");
        names__.push_back("e_tau");
        names__.push_back("e_log_tau");
        names__.push_back("beta_prior_info");
        names__.push_back("e_log_1mp");
        names__.push_back("logit_p_mean");
        names__.push_back("logit_p_sd");
    }


    void get_dims(std::vector<std::vector<size_t> >& dimss__) const {
        dimss__.resize(0);
        std::vector<size_t> dims__;
        dims__.resize(0);
        dims__.push_back(K);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(K);
        dims__.push_back(K);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(NG);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(NG);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(K);
        dims__.push_back(K);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(K);
        dims__.push_back(K);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(N);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(N);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(N);
        dimss__.push_back(dims__);
    }

    template <typename RNG>
    void write_array(RNG& base_rng__,
                     std::vector<double>& params_r__,
                     std::vector<int>& params_i__,
                     std::vector<double>& vars__,
                     bool include_tparams__ = true,
                     bool include_gqs__ = true,
                     std::ostream* pstream__ = 0) const {
        vars__.resize(0);
        stan::io::reader<double> in__(params_r__,params_i__);
        static const char* function__ = "logit_glmm_lrvb_model_namespace::write_array";
        (void) function__; // dummy call to supress warning
        // read-transform, write parameters
        vector_d e_beta = in__.vector_constrain(K);
        matrix_d cov_beta = in__.cov_matrix_constrain(K);
        double e_mu = in__.scalar_constrain();
        double var_mu = in__.scalar_lb_constrain(0);
        double tau_shape = in__.scalar_lb_constrain(0);
        double tau_rate = in__.scalar_lb_constrain(0);
        vector_d e_u = in__.vector_constrain(NG);
        vector_d var_u = in__.vector_lb_constrain(0,NG);
        for (int k_0__ = 0; k_0__ < K; ++k_0__) {
            vars__.push_back(e_beta[k_0__]);
        }
        for (int k_1__ = 0; k_1__ < K; ++k_1__) {
            for (int k_0__ = 0; k_0__ < K; ++k_0__) {
                vars__.push_back(cov_beta(k_0__, k_1__));
            }
        }
        vars__.push_back(e_mu);
        vars__.push_back(var_mu);
        vars__.push_back(tau_shape);
        vars__.push_back(tau_rate);
        for (int k_0__ = 0; k_0__ < NG; ++k_0__) {
            vars__.push_back(e_u[k_0__]);
        }
        for (int k_0__ = 0; k_0__ < NG; ++k_0__) {
            vars__.push_back(var_u[k_0__]);
        }

        if (!include_tparams__) return;
        // declare and define transformed parameters
        double lp__ = 0.0;
        (void) lp__; // dummy call to supress warning
        stan::math::accumulator<double> lp_accum__;

        matrix_d e_beta_outer(static_cast<Eigen::VectorXd::Index>(K),static_cast<Eigen::VectorXd::Index>(K));
        (void) e_beta_outer;  // dummy to suppress unused var warning
        double e_mu2(0.0);
        (void) e_mu2;  // dummy to suppress unused var warning
        double e_tau(0.0);
        (void) e_tau;  // dummy to suppress unused var warning
        double e_log_tau(0.0);
        (void) e_log_tau;  // dummy to suppress unused var warning
        matrix_d beta_prior_info(static_cast<Eigen::VectorXd::Index>(K),static_cast<Eigen::VectorXd::Index>(K));
        (void) beta_prior_info;  // dummy to suppress unused var warning
        vector_d e_log_1mp(static_cast<Eigen::VectorXd::Index>(N));
        (void) e_log_1mp;  // dummy to suppress unused var warning
        vector_d logit_p_mean(static_cast<Eigen::VectorXd::Index>(N));
        (void) logit_p_mean;  // dummy to suppress unused var warning
        vector_d logit_p_sd(static_cast<Eigen::VectorXd::Index>(N));
        (void) logit_p_sd;  // dummy to suppress unused var warning

        try {
            current_statement_begin__ = 54;
            stan::math::assign(e_beta_outer, add(multiply(e_beta,transpose(e_beta)),cov_beta));
            current_statement_begin__ = 55;
            stan::math::assign(e_mu2, (pow(e_mu,2) + var_mu));
            current_statement_begin__ = 56;
            stan::math::assign(e_tau, (tau_shape / tau_rate));
            current_statement_begin__ = 57;
            stan::math::assign(e_log_tau, (digamma(tau_shape) - log(tau_rate)));
            current_statement_begin__ = 60;
            for (int n = 1; n <= N; ++n) {
                current_statement_begin__ = 62;
                stan::math::assign(get_base1_lhs(logit_p_mean,n,"logit_p_mean",1), (dot_product(get_base1(x,n,"x",1),e_beta) + get_base1(e_u,(get_base1(y_group,n,"y_group",1) + 1),"e_u",1)));
                current_statement_begin__ = 63;
                stan::math::assign(get_base1_lhs(logit_p_sd,n,"logit_p_sd",1), sqrt((dot_product(get_base1(x,n,"x",1),multiply(e_beta_outer,get_base1(x,n,"x",1))) + get_base1(var_u,(get_base1(y_group,n,"y_group",1) + 1),"var_u",1))));
                current_statement_begin__ = 67;
                stan::math::assign(get_base1_lhs(e_log_1mp,n,"e_log_1mp",1), 0);
                current_statement_begin__ = 68;
                for (int n_sim = 1; n_sim <= N_sim; ++n_sim) {
                    current_statement_begin__ = 69;
                    stan::math::assign(get_base1_lhs(e_log_1mp,n,"e_log_1mp",1), (get_base1(e_log_1mp,n,"e_log_1mp",1) + log1m_inv_logit(((get_base1(logit_p_sd,n,"logit_p_sd",1) * get_base1(std_normal_draws,n_sim,"std_normal_draws",1)) + get_base1(logit_p_mean,n,"logit_p_mean",1)))));
                }
                current_statement_begin__ = 72;
                stan::math::assign(get_base1_lhs(e_log_1mp,n,"e_log_1mp",1), (get_base1(e_log_1mp,n,"e_log_1mp",1) / N_sim));
            }
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e,current_statement_begin__);
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }

        // validate transformed parameters

        // write transformed parameters
        for (int k_1__ = 0; k_1__ < K; ++k_1__) {
            for (int k_0__ = 0; k_0__ < K; ++k_0__) {
                vars__.push_back(e_beta_outer(k_0__, k_1__));
            }
        }
        vars__.push_back(e_mu2);
        vars__.push_back(e_tau);
        vars__.push_back(e_log_tau);
        for (int k_1__ = 0; k_1__ < K; ++k_1__) {
            for (int k_0__ = 0; k_0__ < K; ++k_0__) {
                vars__.push_back(beta_prior_info(k_0__, k_1__));
            }
        }
        for (int k_0__ = 0; k_0__ < N; ++k_0__) {
            vars__.push_back(e_log_1mp[k_0__]);
        }
        for (int k_0__ = 0; k_0__ < N; ++k_0__) {
            vars__.push_back(logit_p_mean[k_0__]);
        }
        for (int k_0__ = 0; k_0__ < N; ++k_0__) {
            vars__.push_back(logit_p_sd[k_0__]);
        }

        if (!include_gqs__) return;
        // declare and define generated quantities

        double DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning


        // initialize transformed variables to avoid seg fault on val access

        try {
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e,current_statement_begin__);
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }

        // validate generated quantities

        // write generated quantities
    }

    template <typename RNG>
    void write_array(RNG& base_rng,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                     bool include_tparams = true,
                     bool include_gqs = true,
                     std::ostream* pstream = 0) const {
      std::vector<double> params_r_vec(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r_vec[i] = params_r(i);
      std::vector<double> vars_vec;
      std::vector<int> params_i_vec;
      write_array(base_rng,params_r_vec,params_i_vec,vars_vec,include_tparams,include_gqs,pstream);
      vars.resize(vars_vec.size());
      for (int i = 0; i < vars.size(); ++i)
        vars(i) = vars_vec[i];
    }

    static std::string model_name() {
        return "logit_glmm_lrvb_model";
    }


    void constrained_param_names(std::vector<std::string>& param_names__,
                                 bool include_tparams__ = true,
                                 bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        for (int k_0__ = 1; k_0__ <= K; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "e_beta" << '.' << k_0__;
            param_names__.push_back(param_name_stream__.str());
        }
        for (int k_1__ = 1; k_1__ <= K; ++k_1__) {
            for (int k_0__ = 1; k_0__ <= K; ++k_0__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "cov_beta" << '.' << k_0__ << '.' << k_1__;
                param_names__.push_back(param_name_stream__.str());
            }
        }
        param_name_stream__.str(std::string());
        param_name_stream__ << "e_mu";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "var_mu";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "tau_shape";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "tau_rate";
        param_names__.push_back(param_name_stream__.str());
        for (int k_0__ = 1; k_0__ <= NG; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "e_u" << '.' << k_0__;
            param_names__.push_back(param_name_stream__.str());
        }
        for (int k_0__ = 1; k_0__ <= NG; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "var_u" << '.' << k_0__;
            param_names__.push_back(param_name_stream__.str());
        }

        if (!include_gqs__ && !include_tparams__) return;
        for (int k_1__ = 1; k_1__ <= K; ++k_1__) {
            for (int k_0__ = 1; k_0__ <= K; ++k_0__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "e_beta_outer" << '.' << k_0__ << '.' << k_1__;
                param_names__.push_back(param_name_stream__.str());
            }
        }
        param_name_stream__.str(std::string());
        param_name_stream__ << "e_mu2";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "e_tau";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "e_log_tau";
        param_names__.push_back(param_name_stream__.str());
        for (int k_1__ = 1; k_1__ <= K; ++k_1__) {
            for (int k_0__ = 1; k_0__ <= K; ++k_0__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "beta_prior_info" << '.' << k_0__ << '.' << k_1__;
                param_names__.push_back(param_name_stream__.str());
            }
        }
        for (int k_0__ = 1; k_0__ <= N; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "e_log_1mp" << '.' << k_0__;
            param_names__.push_back(param_name_stream__.str());
        }
        for (int k_0__ = 1; k_0__ <= N; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "logit_p_mean" << '.' << k_0__;
            param_names__.push_back(param_name_stream__.str());
        }
        for (int k_0__ = 1; k_0__ <= N; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "logit_p_sd" << '.' << k_0__;
            param_names__.push_back(param_name_stream__.str());
        }

        if (!include_gqs__) return;
    }


    void unconstrained_param_names(std::vector<std::string>& param_names__,
                                   bool include_tparams__ = true,
                                   bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        for (int k_0__ = 1; k_0__ <= K; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "e_beta" << '.' << k_0__;
            param_names__.push_back(param_name_stream__.str());
        }
        for (int k_0__ = 1; k_0__ <= (K + ((K * (K - 1)) / 2)); ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "cov_beta" << '.' << k_0__;
            param_names__.push_back(param_name_stream__.str());
        }
        param_name_stream__.str(std::string());
        param_name_stream__ << "e_mu";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "var_mu";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "tau_shape";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "tau_rate";
        param_names__.push_back(param_name_stream__.str());
        for (int k_0__ = 1; k_0__ <= NG; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "e_u" << '.' << k_0__;
            param_names__.push_back(param_name_stream__.str());
        }
        for (int k_0__ = 1; k_0__ <= NG; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "var_u" << '.' << k_0__;
            param_names__.push_back(param_name_stream__.str());
        }

        if (!include_gqs__ && !include_tparams__) return;
        for (int k_1__ = 1; k_1__ <= K; ++k_1__) {
            for (int k_0__ = 1; k_0__ <= K; ++k_0__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "e_beta_outer" << '.' << k_0__ << '.' << k_1__;
                param_names__.push_back(param_name_stream__.str());
            }
        }
        param_name_stream__.str(std::string());
        param_name_stream__ << "e_mu2";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "e_tau";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "e_log_tau";
        param_names__.push_back(param_name_stream__.str());
        for (int k_1__ = 1; k_1__ <= K; ++k_1__) {
            for (int k_0__ = 1; k_0__ <= K; ++k_0__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "beta_prior_info" << '.' << k_0__ << '.' << k_1__;
                param_names__.push_back(param_name_stream__.str());
            }
        }
        for (int k_0__ = 1; k_0__ <= N; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "e_log_1mp" << '.' << k_0__;
            param_names__.push_back(param_name_stream__.str());
        }
        for (int k_0__ = 1; k_0__ <= N; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "logit_p_mean" << '.' << k_0__;
            param_names__.push_back(param_name_stream__.str());
        }
        for (int k_0__ = 1; k_0__ <= N; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "logit_p_sd" << '.' << k_0__;
            param_names__.push_back(param_name_stream__.str());
        }

        if (!include_gqs__) return;
    }

}; // model

} // namespace

typedef logit_glmm_lrvb_model_namespace::logit_glmm_lrvb_model stan_model;

