# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

SampleData <- function(n_obs, k_reg, n_groups) {
    .Call('LogitGLMMLRVB_SampleData', PACKAGE = 'LogitGLMMLRVB', n_obs, k_reg, n_groups)
}

GetMomentParameterVector <- function(r_vp, unconstrained) {
    .Call('LogitGLMMLRVB_GetMomentParameterVector', PACKAGE = 'LogitGLMMLRVB', r_vp, unconstrained)
}

GetNaturalParameterVector <- function(r_vp, unconstrained) {
    .Call('LogitGLMMLRVB_GetNaturalParameterVector', PACKAGE = 'LogitGLMMLRVB', r_vp, unconstrained)
}

GetMomentParametersFromNaturalParameters <- function(r_vp_nat) {
    .Call('LogitGLMMLRVB_GetMomentParametersFromNaturalParameters', PACKAGE = 'LogitGLMMLRVB', r_vp_nat)
}

GetMomentParametersFromVector <- function(r_vp_base, r_theta, unconstrained) {
    .Call('LogitGLMMLRVB_GetMomentParametersFromVector', PACKAGE = 'LogitGLMMLRVB', r_vp_base, r_theta, unconstrained)
}

GetNaturalParametersFromVector <- function(r_vp_base, r_theta, unconstrained) {
    .Call('LogitGLMMLRVB_GetNaturalParametersFromVector', PACKAGE = 'LogitGLMMLRVB', r_vp_base, r_theta, unconstrained)
}

GetPriorParametersFromVector <- function(r_pp, r_theta, unconstrained) {
    .Call('LogitGLMMLRVB_GetPriorParametersFromVector', PACKAGE = 'LogitGLMMLRVB', r_pp, r_theta, unconstrained)
}

GetPriorParametersVector <- function(r_pp, unconstrained) {
    .Call('LogitGLMMLRVB_GetPriorParametersVector', PACKAGE = 'LogitGLMMLRVB', r_pp, unconstrained)
}

GetPriorsAndNaturalParametersFromVector <- function(r_vp_base, r_pp_base, r_theta, unconstrained) {
    .Call('LogitGLMMLRVB_GetPriorsAndNaturalParametersFromVector', PACKAGE = 'LogitGLMMLRVB', r_vp_base, r_pp_base, r_theta, unconstrained)
}

GetPriorsAndNaturalParametersVector <- function(r_vp_base, r_pp_base, unconstrained) {
    .Call('LogitGLMMLRVB_GetPriorsAndNaturalParametersVector', PACKAGE = 'LogitGLMMLRVB', r_vp_base, r_pp_base, unconstrained)
}

GetLogLikDerivatives <- function(r_y, r_y_g, r_x, r_vp, r_opt) {
    .Call('LogitGLMMLRVB_GetLogLikDerivatives', PACKAGE = 'LogitGLMMLRVB', r_y, r_y_g, r_x, r_vp, r_opt)
}

GetLogPriorDerivatives <- function(r_vp, r_pp, r_opt) {
    .Call('LogitGLMMLRVB_GetLogPriorDerivatives', PACKAGE = 'LogitGLMMLRVB', r_vp, r_pp, r_opt)
}

GetFullModelLogPriorDerivatives <- function(r_vp, r_pp, r_opt) {
    .Call('LogitGLMMLRVB_GetFullModelLogPriorDerivatives', PACKAGE = 'LogitGLMMLRVB', r_vp, r_pp, r_opt)
}

GetLogVariationalDensityDerivatives <- function(r_obs, r_vp, r_opt) {
    .Call('LogitGLMMLRVB_GetLogVariationalDensityDerivatives', PACKAGE = 'LogitGLMMLRVB', r_obs, r_vp, r_opt)
}

GetMCMCLogPriorDerivatives <- function(draw_list, r_pp, r_opt) {
    .Call('LogitGLMMLRVB_GetMCMCLogPriorDerivatives', PACKAGE = 'LogitGLMMLRVB', draw_list, r_pp, r_opt)
}

GetELBODerivatives <- function(r_y, r_y_g, r_x, r_vp, r_pp, r_opt) {
    .Call('LogitGLMMLRVB_GetELBODerivatives', PACKAGE = 'LogitGLMMLRVB', r_y, r_y_g, r_x, r_vp, r_pp, r_opt)
}

GetEntropyDerivatives <- function(r_vp, r_opt) {
    .Call('LogitGLMMLRVB_GetEntropyDerivatives', PACKAGE = 'LogitGLMMLRVB', r_vp, r_opt)
}

GetCovariance <- function(r_vp) {
    .Call('LogitGLMMLRVB_GetCovariance', PACKAGE = 'LogitGLMMLRVB', r_vp)
}

GetMomentJacobian <- function(r_vp, r_opt) {
    .Call('LogitGLMMLRVB_GetMomentJacobian', PACKAGE = 'LogitGLMMLRVB', r_vp, r_opt)
}

GetSparseLogLikHessian <- function(r_y, r_y_g, r_x, r_vp, r_pp, r_opt, include_prior) {
    .Call('LogitGLMMLRVB_GetSparseLogLikHessian', PACKAGE = 'LogitGLMMLRVB', r_y, r_y_g, r_x, r_vp, r_pp, r_opt, include_prior)
}

GetSparseEntropyHessian <- function(r_vp, r_opt) {
    .Call('LogitGLMMLRVB_GetSparseEntropyHessian', PACKAGE = 'LogitGLMMLRVB', r_vp, r_opt)
}

